name: Deploy to demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-demo:
    name: Call reusable workflow on push to main branch
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy.yaml@main
    with:
      app_name: fdk-nginx-altinn-proxy-mock
      environment: demo
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

# Currently not needed, uncomment if deploy to staging is necessary
#  deploy-to-staging:
#    needs: build-and-deploy-demo
#    name: Deploy to staging if demo-deploy is successful
#    uses: Informasjonsforvaltning/workflows/.github/workflows/deploy.yaml@main
#    with:
#      app_name: dataset-catalog-gui
#      environment: staging
#      cluster: digdir-fdk-dev
#    secrets:
#      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
#      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
